### ISSUE TITLE
Mobile Commons Backfill Update

### ISSUE THREAD

**Issue by sheyd** [DoSomethingArchive/northstar-mobilecommonsd#9]
We want to run a backfill of all Mobile Commons numbers to make sure we have an accurate snapshot of all legacy data from the 🌅  of our MC usage. 

@DFurnes Tag me for testing/setup or anything else you need to make this happen.

**Comment by DFurnes** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a developer, I want to test mobile commons backfill on Northstar so that we know we'll have a solid member count when using Quasar.](https://trello.com/c/V0o7L3vF/98-as-a-developer-i-want-to-test-mobile-commons-backfill-on-northstar-so-that-we-know-we-ll-have-a-solid-member-count-when-using-qu)

**Comment by DFurnes** [comment]
And it's now running in production! We'll see how it goes! :v: 🔀
